workspace = { members = ["orig"] }

[package]
name = "wartcl"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
debug = true
panic = "abort"

[dev-dependencies]
criterion = "0.5.1"
partcl-wrapper.path = "orig"

[[bench]]
name = "basic"
harness = false
