[package]
name = "partcl-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2.154", default-features = false }

[build-dependencies]
cc = "1.0.97"
